/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-07-24 09:12:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch09;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String c_name = null;
	Cookie cookies[] = request.getCookies();
	for(int i=0;i<cookies.length;i++){
		out.print("쿠키정보 : "+cookies[i].getValue());
		if(cookies[i].getName().equals("c_name")){
			c_name=cookies[i].getValue();
		}
	}
	if(c_name==null){
		response.sendRedirect("a.jsp");
	}

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Add and Remove Layout - jQuery EasyUI Demo</title>\r\n");
      out.write("    <!-- \r\n");
      out.write("    easyui.css는 jeasyui가 제공하는 콤포넌트(예:datagrid,layout 등)에 \r\n");
      out.write("       디자인을 입힐 때 사용됨\r\n");
      out.write("     -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/default/easyui.css\">\r\n");
      out.write("\t<!-- icon.css는 아이콘 이미지 처리하는데 사용됨 -->   \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/icon.css\">\r\n");
      out.write("    <!-- jeasyui 데모페이지에 사용되는 css임 -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/demo/demo.css\">\r\n");
      out.write("    <!-- jeasyui가 jquery기반이므로 호환성을 검증한 스크립트 코드만 따로 모아둠. -->\r\n");
      out.write("    <!-- <script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script> -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.6.min.js\"></script>\r\n");
      out.write("    <!-- \r\n");
      out.write("    jeasyui가 jquery기반이므로 아래 파일을 import하기 전에 반드시 jquery.min.js\r\n");
      out.write("       가 import되어 있어야 함. 순서 반드시 지킬것. \r\n");
      out.write("     -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar db_name=\"김유신\";\r\n");
      out.write("\t\t//입력화면에서 저장 버튼 클릭했을 때\r\n");
      out.write("\t\t//사용자가 입력한 정보를 서버로(Tomcat) 전송해야 함.\r\n");
      out.write("\t\t//get 인터셉트를 한다. 누가(브라우저) -> 서버로 요청이 전송되지 않음.\r\n");
      out.write("\t\t//한번 요청된 페이지는 각 사용자 PC에 그 내용이 다운로드\r\n");
      out.write("\t\t//두 번째 같은 페이지를 요청하면 서버에 전달한 다음 응답을 받아오는것이 아니라\r\n");
      out.write("\t\t// XXX.html?1 주소창에 다른글자를 한자로 붙이면 새로운 요청으로 인식\r\n");
      out.write("\t    // XXX.html?mem_id=test&mem_pw=123\r\n");
      out.write("\t\t//브라우저가 열릴 때마다 네이버 서버측에서 너에게 세션아이디 \t\t\r\n");
      out.write("\t\t//사용자 컴터에 있는 정보가 그대로 다시 출력된다.\r\n");
      out.write("\t\t//클라이언트측에 다운로드(html,css,js)\r\n");
      out.write("\t\t//<form>태그 -> method->get(default-인터셉트)|post, action->이 요청을 처리해줄 페이지를\r\n");
      out.write("\t\tfunction add(){\r\n");
      out.write("\t\t\t$(\"#f_add\").submit();//전송. 어디로 가는거지?, 전송방식?\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//입력화면에서 취소 버튼 클릭했을 때\r\n");
      out.write("\t\tfunction cancel(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//입력 다이얼로그창 열기\r\n");
      out.write("\t\tfunction addForm(){\r\n");
      out.write("\t\t\t$('#dlg_add').dialog('open');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//수정 다이얼로그창 열기\r\n");
      out.write("\t\tfunction updForm(){\r\n");
      out.write("\t\t\tvar row = $(\"#dg_member\").datagrid(\"getSelected\");\r\n");
      out.write("\t\t\t//datagrid초기화시 소문자로 작성하였으므로 반드시 소문자로 접근해야 함.\r\n");
      out.write("\t\t\t//만일 대문자로 작성하면 undefine\r\n");
      out.write("\t\t\tvar c_id = row.id; \r\n");
      out.write("\t\t\t//alert(c_id);\r\n");
      out.write("\t\t\t//톰캣 서버로 이 아이디와 같은 상세정보를 조회하면 화면에 출력해야함.\r\n");
      out.write("\t\t\tlocation.href=\"./memberUpdateForm.jsp?id=\"+c_id;\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t//이름으로 검색하기\r\n");
      out.write("\t\tfunction nameSearch(){\r\n");
      out.write("\t\t\talert(\"nameSearch호출 성공\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//로그인 요청시 구현\r\n");
      out.write("\t\tfunction loginAction(){\r\n");
      out.write("\t\t\t//front-end언어는 오라클 서버와 연동할 수 없다. - 상수처리한다.\r\n");
      out.write("\t\t\tvar db_id = \"test\";\r\n");
      out.write("\t\t\tvar db_pw = \"123\";\r\n");
      out.write("\t\t\tvar u_id = $(\"#tb_id\").val();\r\n");
      out.write("\t\t\tvar u_pw = $(\"#tb_pw\").val();\r\n");
      out.write("\t\t\tif(db_id==u_id){//아이디가 존재하니\r\n");
      out.write("\t\t\t\tif(db_pw==u_pw){//비번까지 같은거야? 네\r\n");
      out.write("\t\t\t\t\t//로그인폼 숨기고 대신 로그인 성공화면 show\r\n");
      out.write("\t\t\t\t\t$(\"#d_login\").hide();\r\n");
      out.write("\t\t\t\t\t$(\"#d_logout\").show();\r\n");
      out.write("\t\t\t\t\t//span태그에 메시지를 추가  - 김유신님 환영합니다.\r\n");
      out.write("\t\t\t\t\t$(\"#s_msg\").html(\"<b>\"+db_name+\"</b>님 환영합니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{//비번이 틀린거 같아\r\n");
      out.write("\t\t\t\t\talert(\"비번이 틀렸습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#tb_pw\").textbox('setValue','');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{//아이디가 존재하지 않아\r\n");
      out.write("\t\t\t\talert(\"아이디가 없습니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//로그아웃 요청시 구현\r\n");
      out.write("\t\tfunction logoutAction(){\r\n");
      out.write("\t\t\t$(\"#d_logout\").hide();\r\n");
      out.write("\t\t\t$(\"#d_login\").show();\r\n");
      out.write("\t\t\t$(\"#tb_id\").textbox('setValue','');\r\n");
      out.write("\t\t\t$(\"#tb_pw\").textbox('setValue','');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction getRowIndex(target){\r\n");
      out.write("\t\t\tvar tr = $(target).closest('tr.datagrid-row');\r\n");
      out.write("\t\t\treturn parseInt(tr.attr('datagrid-row-index'));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction editrow(target){\r\n");
      out.write("\t\t\talert(\"editrow호출성공 : \"+target);//Object\r\n");
      out.write("\t\t\t$(\"#dg_emp\").datagrid(\"beginEdit\",getRowIndex(target));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction deleterow(target){\r\n");
      out.write("\t\t\talert(\"deleterow호출성공 : \"+target);//Object\r\n");
      out.write("\t\t\t$.messager.confirm('Confirm','정말 삭제하시겠습니까?',function(r){\r\n");
      out.write("\t\t\t    if (r){\r\n");
      out.write("\t\t\t    \tvar vdeptnos=\"\";//10,20,30\r\n");
      out.write("\t\t\t    \tvar deptnoArr=[];//배열 선언\r\n");
      out.write("\t\t\t        //alert('ok');\r\n");
      out.write("\t\t\t        //datagrid생성자 안에 좌중괄호 우중괄호는 필요없다. 왜냐면 실행문 필요없으니깐....\r\n");
      out.write("\t\t\t        var rows = $(\"#dg_emp\").datagrid('getSelections');//속성뒤에 s가 있으면 배열이나 복수형\r\n");
      out.write("\t\t\t        //var array = new Array();\r\n");
      out.write("\t\t\t        if(rows==null){\r\n");
      out.write("\t\t\t        \talert(\"삭제할 사원을 선택하세요.\");\r\n");
      out.write("\t\t\t        \treturn;//deleterow함수를 탈출\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        //DELETE FROM emp WHERE deptno IN(10,20,30);\r\n");
      out.write("\t\t\t        for(var i=0;i<rows.length;i++){\r\n");
      out.write("\t\t\t        \t//alert(rows[i].empno);\r\n");
      out.write("\t\t\t        \tdeptnoArr.push(rows[i].deptno);\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        for(var i=0;i<rows.length;i++){\r\n");
      out.write("\t\t\t      \t\tif(i==rows.length-1){\r\n");
      out.write("\t\t\t      \t\t\tvdeptnos+= deptnoArr[i];\r\n");
      out.write("\t\t\t      \t\t}\r\n");
      out.write("\t\t\t      \t\telse{\r\n");
      out.write("\t\t\t      \t\t\tvdeptnos+= deptnoArr[i]+\",\";\r\n");
      out.write("\t\t\t      \t\t}\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        location.href=\"empDelete.jsp?deptnos=\"+vdeptnos;\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction saverow(target){\r\n");
      out.write("\t\t\talert(\"saverow호출성공 : \"+target);//Object\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cancelrow(target){\r\n");
      out.write("\t\t\t//alert(\"cancelrow호출성공 : \"+target);//Object\r\n");
      out.write("\t\t\t$(\"#dg_emp\").datagrid('cancelEdit',getRowIndex(target));\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t//페이지네이션에서 페이지 이동 버튼을 클릭했을때 오라클 서버에서 조회한 결과를 출력할것.\r\n");
      out.write("\t\tfunction pageMove(pageNumber, pageSize){\r\n");
      out.write("\t\t\t$(\"#dg_emp\").datagrid({\r\n");
      out.write("/*\r\n");
      out.write("SELECT\r\n");
      out.write("       a.rno, a.emp_name\r\n");
      out.write("  FROM (SELECT rownum rno, emp_name FROM temp) a\r\n");
      out.write(" WHERE a.rno >=:s AND a.rno <=:e  \r\n");
      out.write(" 화면에서 사용자가 보고자 하는 페이지에 대한 정보를 자바코드에 전달(페이지수, 사용자가 보고싶은 페이지)해야 함.\r\n");
      out.write(" 톰캣서버에게 전달해야 함.\r\n");
      out.write(" 파라미터로 넘겨받은 값을 활용하여 start값과 end값을 계산해야 함.\r\n");
      out.write(" start값 계산하기\r\n");
      out.write(" start = ((page-1)*pageSize)+1 ;\r\n");
      out.write(" \r\n");
      out.write(" end = page*pageSize;\r\n");
      out.write(" \r\n");
      out.write(" if(end>total){\r\n");
      out.write("\tend = total;\r\n");
      out.write(" }else{\r\n");
      out.write("\tend = end;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" 1   11  21 31  41\r\n");
      out.write("                46\r\n");
      out.write(" 10  20  30 40\r\n");
      out.write("*/\r\n");
      out.write("\t\t\t\turl:'./getEmpList2.jsp?pageNumber='+pageNumber+\"&pageSize=\"+pageSize\r\n");
      out.write("\t\t\t   ,onDblClickCell:function(index,field,value){\r\n");
      out.write("\t\t\t\t   alert(\"더블클릭\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#d_login {\r\n");
      out.write("\t\t    /*border: 1px solid red;*/\r\n");
      out.write("\t\t\twidth: 190px;\r\n");
      out.write("\t\t\theight: 110px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t//날짜 포맷 형식을 디폴트에서 사용자 정의로 변경하므로\r\n");
      out.write("\t//body태그 안에 해당 콤포넌트가 정의되기 전에 처리함.\r\n");
      out.write("\t\t//datebox에 대한 날짜 포맷 재정의함.\r\n");
      out.write("\t\t$.fn.datebox.defaults.formatter = function(date){\r\n");
      out.write("\t\t\tvar y = date.getFullYear();\r\n");
      out.write("\t\t\tvar m = date.getMonth()+1;\r\n");
      out.write("\t\t\tvar d = date.getDate();\r\n");
      out.write("\t\t\treturn y+'-'+(m<10 ? \"0\"+m:m)+'-'+(d<10 ? \"0\"+d:d);\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t//datebox에 날짜 포맷을 적용함.\r\n");
      out.write("\t\t$.fn.datebox.defaults.parser = function(s){\r\n");
      out.write("\t\t\tvar t = Date.parse(s);\r\n");
      out.write("\t\t\tif (!isNaN(t)){\r\n");
      out.write("\t\t\t\treturn new Date(t);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn new Date();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t$(document).ready(function (){\r\n");
      out.write("\t\t\t/* 회원관리에 필요한 데이터그리드 추가  - 설정*/\r\n");
      out.write("\t\t\t$(\"#dg_member\").datagrid({\r\n");
      out.write("\t\t\t    columns:[[\r\n");
      out.write("\t\t\t\t\t{field:'id', title:'아이디', width:100}/* 아이디 */\r\n");
      out.write("\t\t\t\t   ,{field:'name', title:'이름', width:120}/* 이름 */\r\n");
      out.write("\t\t\t\t   ,{field:'address', title:'주소', width:300}/* 주소 */\r\n");
      out.write("\t\t\t\t   ,{field:'hp', title:'H.P', width:140}/* HP */\r\n");
      out.write("\t\t\t\t]]\r\n");
      out.write("\t\t\t\t,singleSelect:'true'\r\n");
      out.write("\t\t\t\t,toolbar:'#tbar_member'\r\n");
      out.write("\t\t\t\t//,url:'./jsonMember.json'\r\n");
      out.write("\t\t\t\t,data: [\r\n");
      out.write("\t\t\t\t\t     {id:\"test\", name:\"김유신\",address:\"서울시 마포구 공덕동\",   hp:\"010-222-2256\"}\r\n");
      out.write("\t\t\t\t        ,{id:\"apple\",name:\"이순신\",address:\"서울시 금천구 가산동\",   hp:\"010-333-1477\"}\r\n");
      out.write("\t\t\t\t        ,{id:\"haha\", name:\"이성계\",address:\"서울시 영등포구 영등포동\", hp:\"010-211-5588\"}\r\n");
      out.write("\t\t\t\t       ]\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});//////////////end of dg_member\r\n");
      out.write("\t\t\t/* 사원관리에 필요한 데이터그리드 추가  - 설정*/\r\n");
      out.write("\t\t\t$(\"#dg_emp\").datagrid({\r\n");
      out.write("\t\t\t\t url:'jsonEmp.json'\r\n");
      out.write("\t\t\t\t,singleSelect:'true'\r\n");
      out.write("\t\t\t\t,toolbar:'#tbar_emp'\r\n");
      out.write("\t\t\t\t,pagination:'true'\r\n");
      out.write("\t\t\t\t//데이터그리드에 url정보를통해서 읽어들인 데이터가 적용되었을 때\r\n");
      out.write("\t\t\t\t,onLoadSuccess:function(data){\r\n");
      out.write("\t\t\t\t\t$(\"#pn_emp\").pagination({\r\n");
      out.write("\t\t\t\t\t\ttotal:data.total\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t    ,onEndEdit:function(index,row){\r\n");
      out.write("                \tvar ed = $(this).datagird('getEditor',{\r\n");
      out.write("                \t\t\t\tindex:index\r\n");
      out.write("                \t         });\r\n");
      out.write("\t             }\r\n");
      out.write("\t\t\t    ,onBeforeEdit:function(index,row){\r\n");
      out.write("                \trow.editing = true;\r\n");
      out.write("                \t$(this).datagrid('refreshRow',index);\r\n");
      out.write("\t             }\r\n");
      out.write("\t\t\t    ,onAfterEdit:function(index,row){\r\n");
      out.write("                \trow.editing = false;\r\n");
      out.write("                \t$(this).datagrid('refreshRow',index);\r\n");
      out.write("\t             }\r\n");
      out.write("\t\t\t     ,onCancelEdit:function(index,row){\r\n");
      out.write("                \trow.editing = false;\r\n");
      out.write("                \t$(this).datagrid('refreshRow',index);\r\n");
      out.write("\t             }\t\t\r\n");
      out.write("\t\t\t});//////////////end of dg_emp\r\n");
      out.write("///////////////////////// 페이지 네이션 추가해 보기 ////////////////////////\t\r\n");
      out.write("/*             $(\"#dg_emp\").datagrid('getPager').pagination({\r\n");
      out.write("            \tlayout:['list','sep','first','prev','links','next','last','sep','refresh']\r\n");
      out.write("        \t}); */\r\n");
      out.write("///////////////////////// 페이지 네이션 추가해 보기 ////////////////////////\t\t\t\r\n");
      out.write(" \t\t\t$(\"#pn_emp\").pagination({\r\n");
      out.write("\t\t\t\tpageList: [1,2,3]\r\n");
      out.write(" \t\t\t   ,pageSize: 1\r\n");
      out.write("               ,showPageList: true\r\n");
      out.write("               ,showRefresh: false\r\n");
      out.write("               //,displayMsg: ''\r\n");
      out.write("               ,onSelectPage: function(pageNumber, pageSize){\r\n");
      out.write("               \t\t//alert(pageNumber+\", \"+pageSize);   \r\n");
      out.write("            \t   pageMove(pageNumber,pageSize);//DB경유해야함.\r\n");
      out.write("               }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("//세개 페이지(회원관리,DVD관리,대여관리) 숨김 처리하기\t\t\t\r\n");
      out.write("\t\t\t$(\"#d_member\").hide();\r\n");
      out.write("\t\t\t$(\"#d_dvd\").hide();\r\n");
      out.write("\t\t\t$(\"#d_rental\").hide();\t\r\n");
      out.write("\t\t\t//로그인 성공했을 때 화면을 숨기자\r\n");
      out.write("\t\t\t$(\"#d_logout\").hide();\r\n");
      out.write("//easyui에서 제공하는 tree객체에 onClick이벤트 처리하기 시작\t\t\t\r\n");
      out.write("\t\t\t$('#te_menu').tree({//따로 함수 선언하지 않고 즉시 처리\r\n");
      out.write("\t\t\t\t//파라미터로 넘어오는 node는 사용자가 선택한 엘리먼트 정보 가짐\r\n");
      out.write("\t\t\t\tonClick: function(node){//트리메뉴 선택했을때 이벤트 처리\r\n");
      out.write("\t\t\t\t\t//alert(node.text);  // alert node text property when clicked\r\n");
      out.write("\t\t\t\t\t//node.text하면 선택한 노드문자열 가져옴.\r\n");
      out.write("\t\t\t\t\tif(\"회원관리\"==node.text){//너 회원관리 누른거야?\r\n");
      out.write("\t\t\t\t\t\t//alert(\"11\");\r\n");
      out.write("\t\t\t\t\t//show메소드 호출하면 화면에 출력되고\r\n");
      out.write("\t\t\t\t\t//hide메소드 호출하면 화면에 숨김 처리됨.\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_member\").show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_emp\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_dvd\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_rental\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(\"사원관리\"==node.text){\r\n");
      out.write("\t\t\t\t\t\t//alert(\"22\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_emp\").show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_member\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_dvd\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_dvd\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_rental\").hide();\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(\"DVD관리\"==node.text){\r\n");
      out.write("\t\t\t\t\t\t//alert(\"22\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_member\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_emp\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_dvd\").show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_rental\").hide();\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(\"대여관리\"==node.text){\r\n");
      out.write("\t\t\t\t\t\t//alert(\"33\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_member\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_emp\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_dvd\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_rental\").show();\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});//////////////end of tree\r\n");
      out.write("\r\n");
      out.write("\t\t});//////////////////end of ready DOM구성이 끝났을 때\r\n");
      out.write("\t</script>\r\n");
      out.write("    <div id=\"cc\" class=\"easyui-layout\" style=\"width:950px;height:550px;\">\r\n");
      out.write("        <div data-options=\"region:'west',split:true\" title=\"코딩놀이\" style=\"width:200px;\">\r\n");
      out.write("\t\t<!-- 여백을 주기 위해 -->\r\n");
      out.write("\t\t<div style=\"margin:10px 0;\"></div>\r\n");
      out.write("<!--============= 로그인 화면 처리 시작 =============-->\t\t\r\n");
      out.write("\t\t<div id=\"d_login\" align=\"center\">\r\n");
      out.write("\t\t\t<input id=\"tb_id\" name=\"mem_id\">\t\r\n");
      out.write("\t\t\t <div style=\"margin:5px 0;\"></div>\r\n");
      out.write("\t\t\t<input id=\"tb_pw\" name=\"mem_pw\">\r\n");
      out.write("\t\t\t <div style=\"margin:5px 0;\"></div>\r\n");
      out.write("\t\t\t<a href=\"javascript:loginAction()\" class=\"easyui-linkbutton\">로그인</a>\t\r\n");
      out.write("\t\t\t<a href=\"javascript:memberAction()\" class=\"easyui-linkbutton\">회원가입</a>\t\r\n");
      out.write("\t\t\t<div id=\"naver_id_login\" style=\"margin-bottom:30px\"></div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tvar naver_id_login = new naver_id_login(\"ik_9iwk0aCNEp85yIYA5\", \"http://localhost:8000/ajax/index_ajax.html\");\r\n");
      out.write("\t\t\t\tvar state = naver_id_login.getUniqState();\r\n");
      out.write("\t\t\t\tnaver_id_login.setButton(\"green\", 3,40);\r\n");
      out.write("\t\t\t\tnaver_id_login.setDomain(\"http://localhost:8000/easyui_layout/layout_1.html\");\r\n");
      out.write("\t\t\t\tnaver_id_login.setState(state);\r\n");
      out.write("\t\t\t\tnaver_id_login.setPopup();\r\n");
      out.write("\t\t\t\tnaver_id_login.init_naver_id_login();\r\n");
      out.write("\t\t\t</script>  \t\t\t\t\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$('#tb_id').textbox({\r\n");
      out.write("\t\t\t    iconCls:'icon-man',\r\n");
      out.write("\t\t\t    iconAlign:'right',\r\n");
      out.write("\t\t\t    prompt:'아이디'\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$('#tb_pw').textbox({\r\n");
      out.write("\t\t\t    iconCls:'icon-lock',\r\n");
      out.write("\t\t\t    iconAlign:'right',\r\n");
      out.write("\t\t\t    prompt:'비밀번호'\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t</script>\t\r\n");
      out.write("\t\t</div><!-- 110px -->\r\n");
      out.write("<!--============= 로그인 화면 처리 끝 =============-->\t\t\r\n");
      out.write("<!--============= 로그아웃 화면 처리 시작 =============-->\t\t\r\n");
      out.write("\t\t<div id=\"d_logout\" align=\"center\">\r\n");
      out.write("\t\t\t<span id=\"s_msg\">ㄹ홀호</span>\r\n");
      out.write("\t\t\t <div style=\"margin:5px 0;\"></div>\r\n");
      out.write("\t\t\t<a href=\"javascript:logoutAction()\" class=\"easyui-linkbutton\">로그아웃</a>\t\r\n");
      out.write("\t\t\t<a href=\"javascript:memberUpdate()\" class=\"easyui-linkbutton\">정보수정</a>\t\t\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("<!--============= 로그아웃 화면 처리 끝 =============-->\t\t\r\n");
      out.write("<!--============== 메뉴 트리 시작 =============--> \r\n");
      out.write("        <ul id=\"te_menu\" class=\"easyui-tree\">\r\n");
      out.write("\t        <li data-options=\"state:'closed'\">\r\n");
      out.write("\t            <span>회원관리</span>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>회원목록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>회원등록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>회원수정</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>회원삭제</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li data-options=\"state:'closed'\">\r\n");
      out.write("\t\t\t\t<span>사원관리</span>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span>사원목록</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span>사원등록</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span>사원수정</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span>사원삭제</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t        <li data-options=\"state:'closed'\">\r\n");
      out.write("\t            <span>DVD관리</span>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>DVD목록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>DVD등록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>DVD수정</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>DVD삭제</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li data-options=\"state:'closed'\">\r\n");
      out.write("\t            <span>대여관리</span>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>대여목록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>대여등록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>대여수정</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>대여삭제</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("<!--============== 메뉴 트리  끝 =============--> \r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-options=\"region:'center',title:'DVD관리시스템'\">\r\n");
      out.write("\t\t<!-- 회원관리 -->\r\n");
      out.write("\t\t     <div style=\"margin:10px 0;\"></div>\r\n");
      out.write("<!-- \r\n");
      out.write("================================================================\r\n");
      out.write("\t회원 관리 페이지 구현\r\n");
      out.write("================================================================\r\n");
      out.write(" -->\t\t     \r\n");
      out.write("\t\t     <div id=\"d_member\">\r\n");
      out.write("\t\t     Home - 회원관리 \r\n");
      out.write("\t\t        <div style=\"margin:10px 0;\"></div>\r\n");
      out.write("\t\t\t\t<table title=\"회원목록\" id=\"dg_member\" width=\"700px\" height=\"450px\" class=\"easyui-datagrid\">\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("<!--============== 회원관리화면에 필요한 툴바 시작 ==============-->\r\n");
      out.write("\t\t\t\t<div id=\"tbar_member\">\r\n");
      out.write("\t\t\t\t<table align='left' width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<!-- 조건 검색 추가 -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<label>이름 : </label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"easyui-searchbox\" data-options=\"prompt:'이름을 입력하세요.',searcher:nameSearch\" style=\"width:140px;\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<label>H.P : </label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"easyui-maskedbox\" mask=\"999-9999-9999\" style=\"width:140px;\"> \r\n");
      out.write("\t\t\t\t\t\t<label>생년월일 : </label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"easyui-datebox\" style=\"width:140;\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- 툴바 버튼 추가 -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"padding:2px 5px;\">\r\n");
      out.write("        \t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\">조회</a>\r\n");
      out.write("\t\t\t\t        <a href=\"javascript:addForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">입력</a>\r\n");
      out.write("\t\t\t\t        <a href=\"javascript:updForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\" plain=\"true\">수정</a>\r\n");
      out.write("\t\t\t\t        <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<!--============== 회원관리화면에 필요한 툴바   끝 ==============-->   \r\n");
      out.write("<!--\r\n");
      out.write("\t============== 회원정보 등록 화면 시작  ==============\r\n");
      out.write("    easyui에서 제공하는 API활용시 주요속성\r\n");
      out.write("    id를 통해서 자바스크립트로 이벤트 처리하거나 옵션 추가 등 기능처리가 이루어짐\r\n");
      out.write("        해당 콤포넌트에 대한 상세 속성들은 data-options에 추가하면 됨\r\n");
      out.write("        자바스크립트 에서도 속성을 추가하거나 변경할 수 있음. - 방법확인해 둘 것.\r\n");
      out.write("        태그 안에서 속성 추가시 더블 쿼테이션 으로 묶어주고 속성과 값은 따로 분리하되 \r\n");
      out.write("        기호는 : 콜론을 사용함.\r\n");
      out.write("        태그 마다 스타일속성을 따로 처리할 때는 style속성에 값 자리에 속성명과 값을 주면 됨.\r\n");
      out.write("        제공되는 콤퍼넌트들은 모두 자바스크립트 코드로도 화면 처리 가능함.\r\n");
      out.write("    2가지 방법에 대해서는 혼자서 반드시 해볼것.\r\n");
      out.write("        외부에 CSS 사용보다는 각 태그 내에 있는 style속성이 우선하여 적용됨.     \r\n");
      out.write("--> \r\n");
      out.write("\t\t\t\t<div id=\"dlg_add\" data-options=\"footer:'#tbar_add', closed:true, cache:false\" class=\"easyui-dialog\" title=\"회원등록\" style=\"width:600px;height:350px;padding:10px\">\r\n");
      out.write("\t\t\t\t\t<form id=\"f_add\" method=\"get\" action=\"memberAdd.jsp\">\t\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t    </form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"tbar_add\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:add()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" plain=\"true\">저장</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:cancel()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" plain=\"true\">취소</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<!--============== 회원정보 등록 화면  끝    ==============-->   \r\n");
      out.write("<!--============== 회원정보 수정 화면 시작  ==============--> \r\n");
      out.write("<!--============== 회원정보 수정 화면  끝    ==============--> \r\n");
      out.write("<!--============== 회원정보 삭제 화면 시작  ==============--> \r\n");
      out.write("<!--============== 회원정보 삭제 화면  끝    ==============-->    \r\n");
      out.write("\t\t     </div>   \r\n");
      out.write("<!-- \r\n");
      out.write("================================================================\r\n");
      out.write("\t회원 관리 페이지 구현\r\n");
      out.write("================================================================\r\n");
      out.write(" -->\t\r\n");
      out.write("<!-- \r\n");
      out.write("================================================================\r\n");
      out.write("\t사원 관리 페이지 구현\r\n");
      out.write("================================================================\r\n");
      out.write(" -->\t\t     \r\n");
      out.write("\t\t     <div id=\"d_emp\">\r\n");
      out.write("\t\t     Home - 사원관리 \r\n");
      out.write("\t\t        <div style=\"margin:10px 0;\"></div>\r\n");
      out.write("\t\t\t\t<table title=\"사원목록\" id=\"dg_emp\" width=\"700px\" height=\"450px\" class=\"easyui-datagrid\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t      <tr>\r\n");
      out.write("\t\t                <th data-options=\"field:'empno',width:80\">사원번호</th>\r\n");
      out.write("\t\t                <!-- valueField는 서버에 넘길 값이므로 부서번호를\r\n");
      out.write("\t\t                     textField는 화면에 출력할 값이므로  부서명을\r\n");
      out.write("\t\t                 -->\r\n");
      out.write("\t\t                <th data-options=\"field:'deptno',width:100,\r\n");
      out.write("\t\t                        formatter:function(value,row){\r\n");
      out.write("\t\t                            return row.deptno;\r\n");
      out.write("\t\t                        },\r\n");
      out.write("\t\t                        editor:{\r\n");
      out.write("\t\t                            type:'combobox',\r\n");
      out.write("\t\t                            options:{\r\n");
      out.write("\t\t                                valueField:'deptno',\r\n");
      out.write("\t\t                                textField:'dname',\r\n");
      out.write("\t\t                                method:'get',\r\n");
      out.write("\t\t                                url:'../easyui_layout/jsonDept.json',\r\n");
      out.write("\t\t                                required:true\r\n");
      out.write("\t\t                            }\r\n");
      out.write("\t\t                        }\">부서명</th>\r\n");
      out.write("\t\t                <th data-options=\"field:'hiredate',width:120,align:'right',editor:{type:'text'}\">입사일자</th>\r\n");
      out.write("\t\t                <th data-options=\"field:'ename',width:80,align:'right',editor:{type:'text'}\">사원명</th>\r\n");
      out.write("\t\t                <th data-options=\"field:'Action', width:100, align:'center',\r\n");
      out.write("\t\t                \tformatter:function(value,row,index){\r\n");
      out.write("\t\t                \t\tif(row.editing){\r\n");
      out.write("\t\t                \t\t\tvar s='<a href=# onclick=saverow(this)>Save</a>';\r\n");
      out.write("\t\t                \t\t\tvar c='<a href=# onclick=cancelrow(this)>Cancel</a>';\r\n");
      out.write("\t\t                \t\t\treturn s+' '+c;\t\r\n");
      out.write("\t\t                \t\t}\r\n");
      out.write("\t\t                \t\telse{\r\n");
      out.write("\t\t                 \t\t\tvar e='<a href=# onclick=editrow(this)>Edit</a>';\r\n");
      out.write("\t\t                \t\t\tvar d='<a href=# onclick=deleterow(this)>Delete</a>';\r\n");
      out.write("\t\t                \t\t\treturn e+' '+d;\t               \t\t\r\n");
      out.write("\t\t                \t\t}\r\n");
      out.write("\t\t                \t}\r\n");
      out.write("\t\t                \">Action</th>\r\n");
      out.write("\t\t\t\t            </tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write(" \t\t\t\t<table id=\"pn_emp\" class=\"easyui-pagination\" width=\"700px\" height=\"30px\" style=\"background:#efefef;border:1px solid #ccc;\">\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("<!--============== 회원관리화면에 필요한 툴바 시작 ==============-->\r\n");
      out.write("\t\t\t\t<div id=\"tbar_emp\">\r\n");
      out.write("\t\t\t\t<table align='left' width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<!-- 조건 검색 추가 -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<label>이름 : </label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"easyui-searchbox\" data-options=\"prompt:'이름을 입력하세요.',searcher:nameSearch\" style=\"width:140px;\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<label>H.P : </label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"easyui-maskedbox\" mask=\"999-9999-9999\" style=\"width:140px;\"> \r\n");
      out.write("\t\t\t\t\t\t<label>생년월일 : </label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"easyui-datebox\" style=\"width:140;\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- 툴바 버튼 추가 -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"padding:2px 5px;\">\r\n");
      out.write("        \t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\">조회</a>\r\n");
      out.write("\t\t\t\t        <a href=\"javascript:addForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">입력</a>\r\n");
      out.write("\t\t\t\t        <a href=\"javascript:updForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\" plain=\"true\">수정</a>\r\n");
      out.write("\t\t\t\t        <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<!--============== 회원관리화면에 필요한 툴바   끝 ==============-->   \r\n");
      out.write("<!--============== 회원정보 등록 화면  끝    ==============-->   \r\n");
      out.write("<!--============== 회원정보 수정 화면 시작  ==============--> \r\n");
      out.write("<!--============== 회원정보 수정 화면  끝    ==============--> \r\n");
      out.write("<!--============== 회원정보 삭제 화면 시작  ==============--> \r\n");
      out.write("<!--============== 회원정보 삭제 화면  끝    ==============-->    \r\n");
      out.write("\t\t     </div>   \r\n");
      out.write("<!-- \r\n");
      out.write("================================================================\r\n");
      out.write("\t회원 관리 페이지 구현\r\n");
      out.write("================================================================\r\n");
      out.write(" -->\t \t\t\t\r\n");
      out.write("\t\t<!-- DVD관리 -->\r\n");
      out.write("\t\t     <div id=\"d_dvd\">DVD</div>   \r\n");
      out.write("\t\t<!-- 대여관리 -->        \r\n");
      out.write("\t\t     <div id=\"d_rental\">대여</div>   \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
